name: Pull-Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rancher/dapper:v0.5.4
    steps:
      - uses: actions/checkout@v1
      - name: Run CI
        run: dapper ci

  build-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Build binaries
      env:
        CROSS: false
      run: make build

    - name: Checkout charts Repo
      uses: actions/checkout@v3
      with:
        repository: rancher/charts
        path: charts

    - name: Run Validation
      run: |
        cd charts
        ../bin/charts-build-scripts validate