name: Lint and Test Build

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Run goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: build --snapshot
